dataset:
  category:
  - carpet
  dataset_path: /root/autodl-tmp/mvtec_anomaly_detection
  dataset_type: mvtec
  meta_file: null
model:
  guidance_scale: 0.1
  model_type: idea7
  n_steps: 400
test:
  results_dir: ./results
  save_heatmaps: true
train:
  batch_size: 4
  device: cuda
  epochs: 200
  lambda_flow: 1.0
  lr: 0.0002
  results_dir: ./results
